name: kbm_carwash_admin
description: "KBM Car wash admin portal. The portal is used to administer the car washing business"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  carousel_slider: ^4.2.1
  supabase_flutter: ^2.3.4
  firebase_analytics: ^10.8.9
  google_maps_flutter: ^2.5.3
  firebase_messaging: ^14.7.19
  permission_handler: ^11.3.0
  validation_pro: ^1.1.0
  email_validator: '^2.1.16'
  logger: ^2.0.2+1
  flutter_holo_date_picker: ^1.1.3
  date_format: ^2.0.7
  http: ^1.2.0
  intl: ^0.18.1
  build_runner: ^2.4.7
  adaptive_navbar: ^0.0.2
  responsive_table: ^0.2.0+2
  multiselect: ^0.1.0
  flutter_typeahead: ^5.0.1
  amplify_flutter: ^1.6.1
  file_picker: ^6.1.1
  screenshot: ^2.1.0
  path_provider: ^2.1.2
  flutter_form_builder: ^9.1.1
  amazon_cognito_identity_dart_2: ^3.6.0
  amplify_auth_cognito: ^1.4.2
  amplify_authenticator: ^1.4.2
  flutter_spinner_time_picker: ^0.2.1
  multi_charts: ^0.3.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/car-promo1.jpeg
    - lib/assets/car-promo2.jpeg
    - lib/assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
