name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch name for deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            11
            17
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'  # Change to your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Clean
        run: flutter clean
        
      - name: Build web
        run: flutter build web --release

      - name: Commit changes
        run: |
          git config --global user.name 'Monageng'
          git config --global user.email 'monageng2010@gmail.com'
          git add build/web
          git commit -m "Build Flutter artifacts - Build #$GITHUB_RUN_NUMBER"
          git push
          
